### ISSUE TITLE
How do you wrap help output?

### ISSUE THREAD

**Issue by rcdailey** [Tyrrrz/CliFx#106]
I'd like to have long help text (for subcommands and options) to be hard-wrapped at some specified column. Right now it is soft wrapped by the terminal, which doesn't look very pretty. Aesthetically, the hard wrapped lines should also be indented to align with the start of the first line, so it doesn't get mixed in with the options column itself. Below is an example screenshot of what I'm seeing

![image](https://user-images.githubusercontent.com/1768054/115263932-754abd80-a0fb-11eb-9dce-3f423b4c3115.png)

**Comment by Tyrrrz** [comment]
You can't. I mean, you can insert line breaks right in the description, but the framework doesn't provide any control for that.
