### ISSUE TITLE
Show usage of child commands for their parent in help text

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliFx#11]
For a command that has child commands sub1 and sub2 show the subcommands in usage.

```
Usage
  myapp command [options]
  myapp command sub1 [options]
  myapp command sub2 [options]
```

Probably best to implement this after #10

**Comment by Tyrrrz** [comment]
The idea here is to make it easier for the user to tell how the subcommands work without having to query help on a subcommand.

Example (it doesn't actually do that):

```
> docker container --help

Usage
   docker container [options]
   docker container ls [options]
   docker container kill <id> [options]
```

**Comment by ADustyOldMuffin** [comment]
I'd like to also take this one on.

**Comment by Tyrrrz** [comment]
Go ahead.
