### ISSUE TITLE
Assembly binding confusion results in many AD0001 analyzer warnings

### ISSUE THREAD

**Issue by fossbrandon** [Tyrrrz/CliFx#127]
### Version

2.2.3

### Details

I upgraded from CliFx version 2.2.2 to version 2.2.3 because I wanted those fixes for `IConsole.ReadKey()`, however when I rebuild my solution, it results in lots of `AD0001` analyzer warnings each which look like it originates from the CliFx analyzer.

Here is an example of one of the warnings: 

```
AD0001	Analyzer 'Roslynator.CSharp.Analysis.DefaultExpressionAnalyzer' threw an exception of type
'System.InvalidCastException' with message '[A]Microsoft.CodeAnalysis.CSharp.CSharpCompilation cannot be cast to 
[B]Microsoft.CodeAnalysis.CSharp.CSharpCompilation. Type A originates from 'Microsoft.CodeAnalysis.CSharp, 
Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' in the context 'Default' at location 
'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CodeAnalysis.CSharp.dll'. 
Type B originates from 'Microsoft.CodeAnalysis.CSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
in the context 'LoadFrom' at location 'C:\Users\branfoss\.nuget\packages\clifx\2.2.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.dll'.'.
```

Each warning follows a similar format. 

I've tried the following to remove the warnings with no success:

- Using visual studio, I cleaned and then built the solution
- I've restarted visual studio and tried the first solution again
- I've restarted my PC and tried the first solution again
- I've unloaded each project and reloaded them again followed by the first solution

Has anyone else seen this issue? Downgrading back to version 2.2.2 removes these warnings.

### Steps to reproduce

- Upgrade a project using CliFx to version 2.2.3
- Using Visual Studio, rebuild the solution
- Open the error list view and observe new analyzer warnings

**Comment by fossbrandon** [comment]
I did more experimenting and I can't get these warnings to show up when doing `dotnet build` with the command line. This could be a Visual Studio bug then but it seems odd that I only seem to get those warnings when I update this package to the newest version. Something to look into at least.

**Comment by Tyrrrz** [comment]
Interesting. I've seen other warnings (also very inconsistently) but not this one. Building analyzers is unfortunately such a mess.

Are all the warnings you get the same as the first one?

**Comment by fossbrandon** [comment]
This one is very weird because everytime I rebuild it's a different number of warnings with small deviations in which ones show up. For the most part, they all look like this.

![image](https://user-images.githubusercontent.com/46940941/164565863-e28409f1-7022-4ff0-a77f-2314852c4159.png)

**Comment by Tyrrrz** [comment]
So it looks like there are two `Microsoft.CodeAnalysis.CSharp` assemblies:

1. one packaged within the CliFx nuget package
2. default one packaged with Visual Studio

For some reason, unrelated analyzers (StyleCop, Roslynator in your case) are binding to CliFx's instance of `Microsoft.CodeAnalysis.CSharp` instead of the default one. My assumption is that VS loads all analyzers in the same application domain and that's why the assembly confusion happens (it's also why the order may be different, it depends on which assembler gets picked first). And then `dotnet build` probably loads each analyzer independently.

**Comment by fossbrandon** [comment]
I believe it. The weird thing about my scenario is that every time I rebuild, it gives me a different amount of warnings. It shows anywhere between 33 warnings to 150+ warnings.

They all look like the warning in my initial post, but randomly I get a different error like the middle one in this screenshot.
![image](https://user-images.githubusercontent.com/46940941/164566182-4542300a-5231-44d4-a705-a6288f23fa49.png)

The CliFx analyzer seem to still be working:
![image](https://user-images.githubusercontent.com/46940941/164566254-a1528809-2704-444c-8343-b4fb3545920b.png)

**Comment by Tyrrrz** [comment]
I wonder what's the best thing to do in this case. I'm packaging `Microsoft.CodeAnalysis.CSharp` to ensure that it's available in that specific version. Relying on pre-installed version is risky because it may be different depending on the version of IDE/SDK installed and potentially a million other factors.

**Comment by Tyrrrz** [comment]
Looks like StyleCop's approach is just to use the oldest version of the library :/

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/9c5d064f100186515bcb45aadd629f18bc523a28/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.csproj#L32

**Comment by fossbrandon** [comment]
I don't like that haha. Roslynator uses a fairly recent version it seems. 
https://github.com/JosefPihrt/Roslynator/blob/master/src/Analyzers/Analyzers.csproj#:~:text=%3CPackageReference%20Include%3D%22Microsoft.CodeAnalysis.CSharp%22%20Version%3D%224.0.1%22%20/%3E

**Comment by Tyrrrz** [comment]
Found this on someone's blog:

![image](https://user-images.githubusercontent.com/1935960/164723998-6eb3a6cf-6186-4ad3-87de-551ccb6cc840.png)

Amazing 🙃

**Comment by Tyrrrz** [comment]
@fossbrandon I've pushed a pre-release version here: https://www.nuget.org/packages/CliFx/2.2.4-test

Can you test that:

1. The warnings disappear (make sure to clean your solution just in case before)
2. The analyzers are still working

**Comment by fossbrandon** [comment]
After upgrading, all the warnings are gone!

The CliFx analyzer still seems to work and I was able to get some errors from stylecop so I believe my other analyzers still work as well.

Thanks for looking into this so quick!

**Comment by Tyrrrz** [comment]
Great! I'll push a stable release then
