### ISSUE TITLE
`FakeInMemoryConsole.Clear()` has no effect

### ISSUE THREAD

**Issue by markopolo89** [Tyrrrz/CliFx#129]
### Version

2.2.6

### Details

Sorry if this is not the correct place for this post - I'm not sure if this is a bug. 
I’ve been using your excellent framework to process command line style messages transmitted across a websocket interface. In this scenario, rather than view command exceptions and other messages on the console output it would be convenient to intercept these and send back to the client. For this purpose, I have tried replacing the console window with a FakeInMemoryConsole. This works well, however I have noticed that the clear command does not work. It would be great to be able to check the fake console for reported messages and send them to the client, then clear for next time.

Also, I realise that FakeInMemoryConsole is intended primarily for test purposes but this seems to be the best way to meet my requirement. I was wondering if there is another way to capture the console output?

### Steps to reproduce

- Provide FakeInMemoryConsole object when building the application.
- Call command incorrectly so an exception is produced.
- Intercept the exception message.
- Call the clear method on the FakeInMemoryConsole object.
- FakeInMemoryConsole object does not clear.

**Comment by Tyrrrz** [comment]
Hi.

Indeed, the `Clear()` method doesn't do anything in `FakeConsole`. It may make sense to make it virtual and override in `FakeInMemoryConsole` to clear the in-memory streams.

That said, I'm not sure if it's the best solution for your problem. Can you give some example of what you're trying to achieve? I think, in your situation, I would not write to the console at all, but instead use some sort of logging abstraction and configure it to send data to your websocket interface.

**Comment by markopolo89** [comment]
Thanks for the suggestion. I'll investigate this further. As an interim measure I have replicated the FakeInMemoryConsole and added a clear method to clear the memory streams. This gets me moving for my current task.

**Comment by Tyrrrz** [comment]
> Thanks for the suggestion. I'll investigate this further. As an interim measure I have replicated the FakeInMemoryConsole and added a clear method to clear the memory streams. This gets me moving for my current task.

Would you wanna submit a PR on this? I think having `Clear()` do that in `FakeInMemoryConsole` makes sense.
