### ISSUE TITLE
Create Abstractions Package

### ISSUE THREAD

**Issue by thegreatco** [Tyrrrz/CliFx#21]
Create a package with the interfaces (such as `IConsole`) to allow for custom implementations without importing the whole library.

# Use Case
For referencing the abstractions package in a common library that may be used across CLI, UI, Web applications. For example, a `Logger` that can take an `IConsole` as a parameter and wrap the output. Allowing for methods like `Error()`, `Information()` etc, that can add extra information (like timestamps, colors, etc).

# Suggested Implementation
Move the following interfaces to the package
* `IConsole`
* `ICommand`
* `ICliApplication`
* `ICliApplicationBuilder`
* `ICommandFactory`

It may be helpful to include all of the core interfaces in here, however I leave that up to you.

**Comment by Tyrrrz** [comment]
I think, given that CliFx targets .NET Standard 2.0, it's fine if you just include the full library and only use abstractions in your project.

**Comment by Tyrrrz** [comment]
Closing as won't fix because I don't see enough value on this and want to concentrate my efforts.
