### ISSUE TITLE
After upgrading from 0.0.8 to 1.0.0, Dependency injection management using Autofac failed.

### ISSUE THREAD

**Issue by xknife-erian** [Tyrrrz/CliFx#43]
`using Autofac;`
```
            var builder = new ContainerBuilder();
            builder.RegisterAssemblyModules(typeof(Logic.Global).Assembly);

            builder.RegisterType<SerialCliCommand>().Named<ICommand>("serial").SingleInstance();
            builder.RegisterType<CareConfigCliCommand>().Named<ICommand>("cc").SingleInstance();
            builder.RegisterType<CareCliCommand>().Named<ICommand>("ci").SingleInstance();
            builder.RegisterType<DataCommand>().Named<ICommand>("d").SingleInstance();

            var container = builder.Build();

            await new CliApplicationBuilder()
                .AddCommandsFromThisAssembly()
                .UseTypeActivator(type => container.ResolveNamed<ICommand>(type.Name))
                .Build()
                .RunAsync(args);
```

**Comment by Tyrrrz** [comment]
Hi.
By "failed", what do you mean? What exactly happens?

**Comment by Tyrrrz** [comment]
I think you are resolving a named instance. Previously `UseCommandFactory` provided a `CommandSchema` which had a command name, but now it's just a `Type`. You need to resolve the command by type, not by name.

**Comment by xknife-erian** [comment]
thank you
I come from a non-english speaking country and may not express clearly.
I mean, it was normal to use Autofac, but I want to be able to use it after the upgrade, not report errors.
According to your reply, I have fixed the problem.Thank you very much.
Your project is also a very well designed project, which I have used in many of my projects.

**Comment by Tyrrrz** [comment]
Don't worry 🙂 
I'm glad you've managed to fix the problem and also glad that you like the project!
