### ISSUE TITLE
order changes parser beaviour

### ISSUE THREAD

**Issue by sommmen** [Tyrrrz/CliFx#45]
For some reason the first sample below works, but the second does not. For some reason the ordening of the options change the behaviour of the parser (or i'm missing something).

```
1>  "C:\Repos\HMI4\Tools\HmiPluginDllManager\bin\Debug\netcoreapp3.1\HmiPluginDllManager.exe" [preview] CpyPluginDlls -p "WebHmi.HmiPlugins" -c "Debug" -o "C:\Repos\HMI4\Machines\Kytl320\HmiUiKytl320\bin\Debug\"
Parser preview:
CpyPluginDlls [-p WebHmi.HmiPlugins] [-c Debug] [-o C:\Repos\HMI4\Machines\Kytl320\HmiUiKytl320\bin\Debug"] 
```

```
"C:\Repos\HMI4\Tools\HmiPluginDllManager\bin\Debug\netcoreapp3.1\HmiPluginDllManager.exe" [preview] CpyPluginDlls -p "WebHmi.HmiPlugins" -o "C:\Repos\HMI4\Machines\Kytl320\HmiUiKytl320\bin\Debug\" -c "Debug"
Parser preview:
CpyPluginDlls [-p WebHmi.HmiPlugins] [-o 
 C:\Repos\HMI4\Machines\Kytl320\HmiUiKytl320\bin\Debug" -c Debug"] 
```

**Comment by Tyrrrz** [comment]
Looks like the last quote is actually escaped because you put `\"` in the file path which escapes the quote.

**Comment by sommmen** [comment]
> Looks like the last quote is actually escaped because you put `\"` in the file path which escapes the quote.

You're right - I was looking like a madman for this issue. Much obliged!

**Comment by Tyrrrz** [comment]
No problem.

**Comment by sommmen** [comment]
I am calling this script via MSBuild, so "$(ProjectDir)$(OutDir)" got expanded to the path with the / at the end, then ofcourse came the quote so when that was passed to cmd.exe it escaped it...

**Comment by Tyrrrz** [comment]
One thing you can do is replace the backslashes with forward slashes, those are also supported in paths and don't cause issues.
