### ISSUE TITLE
Validate attributes with analyzers

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliFx#5]
Add analyzers as part of a nuget package to validate attribute usage at the time the code is written.

**Comment by thorhj** [comment]
@Tyrrrz what kinds of validation do you have in mind exactly?

**Comment by thorhj** [comment]
Is it possible/sensible to add an analyzer to the consumer project when adding this NuGet package? I am not experienced with analyzers, but the above validations could easily be checked by a `.targets` files, albeit at build time.

**Comment by Tyrrrz** [comment]
I haven't made an analyzer myself yet :)
From my experience using [open API analyzers for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-3.0&tabs=visual-studio), it's just a NuGet package you add to the consumer project. Analyzers can both point out issues as well as quick fixes.

I'm not sure how to make validations like that with `.targets` files, do you have an example?

**Comment by thorhj** [comment]
I must have misremembered, it does not seem to be easily doable as an MSBuild task. `Microsoft.NET.Sdk.Functions` has a task that (among other things) check validate uniqueness of Function names, but that is done by a separate console application.

**Comment by Tyrrrz** [comment]
Yeah, so it seems it has to be done through the analyzer API.

Generally, I would like all validation that happens in `CommandSchemaResolver` to happen at build time. That would make the feedback loop shorter and improve user experience.

https://github.com/Tyrrrz/CliFx/blob/25cbfdb4b85a6cf5b79926a20e4523de73daf825/CliFx/Services/CommandSchemaResolver.cs#L15-L122

**Comment by Tyrrrz** [comment]
It's happening:

https://twitter.com/Tyrrrz/status/1254035827337953280
