### ISSUE TITLE
Add support for getting the input command

### ISSUE THREAD

**Issue by WajahatAliAbid** [Tyrrrz/CliFx#60]
Need to add support for getting original command entered at start. I've encountered a scenario where I needed to store the original command, although could not find anything for it. If there is, can you point me towards it?

**Comment by Tyrrrz** [comment]
Do you mean `Environment.GetCommandLineArgs()`?

**Comment by WajahatAliAbid** [comment]
Yes, I forgot that was an option. Thanks!
