### ISSUE TITLE
Multiple characters for short name

### ISSUE THREAD

**Issue by ADustyOldMuffin** [Tyrrrz/CliFx#69]
From using other CLI tools it's common to have multiple character short names to avoid clashing of commands I.E. `--save, -s` `--saveFile, -sf`

Is it possible that support for this could be added?

**Comment by Tyrrrz** [comment]
No, because multiple single characters are treated separately, so `-sf` is evaluated as `-s -f`. This comes as a result of CliFx's context-agnostic design philosophy.
