### ISSUE TITLE
Add support for loading arguments from a file

### ISSUE THREAD

**Issue by marktoman** [Tyrrrz/CliFx#75]
Thank you for this amazing framework, first of all.

One general issue in the case of similar frameworks is specifying persistent values for parameters. Environment variables work well for ad-hoc runtime replacement, but if they are the only way to achieve this, an ugly starter script is required to run your app.

To solve this well, I propose adding support for Generic Host. The reason is that it has thought-through support for config files that can be easily overridden for development, production, and so on, and even by environment variables. I think it could live side by side with the current options, which are just great.

**Comment by Tyrrrz** [comment]
I decided that loading arguments from a file is also too niche of a use case. You can plug CliFx into generic host instead, using code as examplified here: https://github.com/Tyrrrz/CliFx/issues/22
