### ISSUE TITLE
Semantic highlighting for exception messages

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/CliFx#78]
Spectre.Console has a feature where it parses and highlights different parts of exception messages.

See [here](https://twitter.com/firstdrafthell/status/1312139828960530432?s=20):

![image](https://user-images.githubusercontent.com/1935960/94978613-decff980-0526-11eb-9311-d066eff15a20.png)

It looks cool! We should steal it!

**Comment by 89netraM** [comment]
Hello,  
This seems like a fun challenge, I'd like to work on it.

I've been looking though the code, and just to make sure I've understood it correctly: The part that needs the change is the `WriteError` method in `CliApplication`  
https://github.com/Tyrrrz/CliFx/blob/8e1488c395b66a9b648b3531945fddddf9086e70/CliFx/CliApplication.cs#L41  
Right? And maybe an option in `ApplicationConfiguration` to allow for a compact mode.

**Comment by Tyrrrz** [comment]
Hi.
Yup, that sounds right.
